language: python
python:
  - "3.8"
  - "3.9"
  - "3.10-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest tests --cov=okama/
after_success:
  - coveralls
