[tool.poetry]
name = "okama"
version = "1.1.2"
description = "Modern Portfolio Theory (MPT) Python package"
authors = ["Sergey Kikevich <sergey@rostsber.ru>"]
license = "MIT"
homepage = "https://okama.io"
repository = "https://github.com/mbk-dev/okama"
documentation = "https://okama.readthedocs.io/en/master"
readme = "README.md"
keywords = ["finance", "investments", "efficient frontier", "python", "optimization"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = ">=0.25.0"
numpy = ">=1.16.5"
scipy = ">=0.14.0"
matplotlib = "^3.5.1"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
nbmake = "^1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
